---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-game-app-deployment
  labels:
    app: my-game-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-game-app
  template:
    metadata:
      labels:
        app: my-game-app
    spec:
      containers:
      - name: my-app-container
        image: 659840170574.dkr.ecr.eu-west-1.amazonaws.com/neeha-ecr-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-game-app-service
spec:
  selector:
    app: my-game-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---